export const teams = [
    {value: 'ARI', label: 'Arizona Cardinals'},
    {value: 'ATL', label: 'Atlanta Falcons'},
    {value: 'BAL', label: 'Balitmore Ravens'},
    {value: 'BUF', label: 'Buffalo Bills'},
    {value: 'CAR', label: 'Carolina Panthers'},
    {value: 'CHI', label: 'Chicago Bears'},
    {value: 'CIN', label: 'Cincinnati Bengals'},
    {value: 'CLE', label: 'Cleveland Browns'},
    {value: 'DAL', label: 'Dallas Cowboys'},
    {value: 'DEN', label: 'Denver Broncos'},
    {value: 'DET', label: 'Detroit Lions'},
    {value: 'GB', label: 'Green Bay Packers'},
    {value: 'HOU', label: 'Houston Texans'},
    {value: 'IND', label: 'Indianaplois Colts'},
    {value: 'JAX', label: 'Jacksonville Jaguars'},
    {value: 'KC', label: 'Kansas City Chiefs'},
    {value: 'LAC', label: 'Los Angeles Chargers'},
    {value: 'LAR', label: 'Los Angeles Rams'},
    {value: 'LV', label: 'Las Vegas Raiders'},
    {value: 'MIA', label: 'Miami Dolphins'},
    {value: 'MIN', label: 'Minnesota Vikings'},
    {value: 'NE', label: 'New England Patriots'},
    {value: 'NO', label: 'New Orlean Saints'},
    {value: 'NYG', label: 'New York Giants'},
    {value: 'NYJ', label: 'New York Jets'},
    {value: 'PHI', label: 'Philadelphia Eagles'},
    {value: 'PIT', label: 'Pittsburgh Steelers'},
    {value: 'SEA', label: 'Seattle Seahawks'},
    {value: 'SF', label: 'San Francisco 49ers'},
    {value: 'TB', label: 'Tampa Bay Buccaneers'},
    {value: 'TEN', label: 'Tennessee Titans'},
    {value: 'WAS', label: 'Washington Team'},
]
export const positions = [
    {value: 'QB', label: 'Quarterback'},
    {value: 'RB', label: 'Running back'},
    {value: 'WR', label: 'Receiver'},
    {value: 'TE', label: 'Tight end'},
    {value: 'K', label: 'Kicker'},
]